#BBL Fixes Startup Config
["BBL Fixes"]
	#Enable Storage Drawers for stacks over 99, requires Storage Drawers mod, default = false
	"Enable Storage Drawers fix" = false
	#Enable Strainers for stacks over 99 with compactor, requires Strainers mod, default = false
	"Enable Strainers fix" = true
	#Fixed Portal JS crashes when player uses flint and steel by making my mixin run first, requires PortalJS mod, default = false
	"Enable PortalJS fix" = false
	#Prevent Block Breaker from breaking bedrock and other unbreakable blocks, requires Opolis Utilities mod, default = false
	"Enable Block Breaker fix" = false
	#Prevent vanilla buckets obtaining a purity tag when collected in world with Thirst Was Taken Mod, requires Thirst Was Taken, default = false
	"Enable bucket fix" = false
	#Changes height level check for Derrick from Immersive Petroleum to prevent water from levels below 64
	"Enable Immersive Petroleum fix" = false
	#Fixed Distillation Tower recipe output disappearing after some time
	"Enable Immersive Petroleum Distillation Tower fix" = false
