ClientEvents.lang('en_us', e => {
  e.renameItem('justdirethings:ferricore_helmet', 'Ferricore Spacesuit Helmet')
  e.renameItem('justdirethings:ferricore_chestplate', 'Ferricore Spacesuit Chestplate')
  e.renameItem('justdirethings:ferricore_leggings', 'Ferricore Spacesuit Leggings')
  e.renameItem('justdirethings:ferricore_boots', 'Ferricore Spacesuit Boots')
  e.renameItem('justdirethings:blazegold_helmet', 'Blazegold Spacesuit Helmet')
  e.renameItem('justdirethings:blazegold_chestplate', 'Blazegold Spacesuit Chestplate')
  e.renameItem('justdirethings:blazegold_leggings', 'Blazegold Spacesuit Leggings')
  e.renameItem('justdirethings:blazegold_boots', 'Blazegold Spacesuit Boots')
  e.renameItem('justdirethings:celestigem_helmet', 'Celestigem Spacesuit Helmet')
  e.renameItem('justdirethings:celestigem_chestplate', 'Celestigem Spacesuit Chestplate')
  e.renameItem('justdirethings:celestigem_leggings', 'Celestigem Spacesuit Leggings')
  e.renameItem('justdirethings:celestigem_boots', 'Celestigem Spacesuit Boots')
  e.renameItem('justdirethings:eclipsealloy_helmet', 'Eclipse Alloy Spacesuit Helmet')
  e.renameItem('justdirethings:eclipsealloy_chestplate', 'Eclipse Alloy Spacesuit Chestplate')
  e.renameItem('justdirethings:eclipsealloy_leggings', 'Eclipse Alloy Spacesuit Leggings')
  e.renameItem('justdirethings:eclipsealloy_boots', 'Eclipse Alloy Spacesuit Boots')
})

ClientEvents.lang('ru_ru', e => {
  e.renameItem('justdirethings:ferricore_helmet', 'Шлем скафандра из Ferricore')
  e.renameItem('justdirethings:ferricore_chestplate', 'Нагрудник скафандра из Ferricore')
  e.renameItem('justdirethings:ferricore_leggings', 'Поножи скафандра из Ferricore')
  e.renameItem('justdirethings:ferricore_boots', 'Ботинки скафандра из Ferricore')
  e.renameItem('justdirethings:blazegold_helmet', 'Шлем скафандра из Blazegold')
  e.renameItem('justdirethings:blazegold_chestplate', 'Нагрудник скафандра из Blazegold')
  e.renameItem('justdirethings:blazegold_leggings', 'Поножи скафандра из Blazegold')
  e.renameItem('justdirethings:blazegold_boots', 'Ботинки скафандра из Blazegold')
  e.renameItem('justdirethings:celestigem_helmet', 'Шлем скафандра из Celestigem')
  e.renameItem('justdirethings:celestigem_chestplate', 'Нагрудник скафандра из Celestigem')
  e.renameItem('justdirethings:celestigem_leggings', 'Поножи скафандра из Celestigem')
  e.renameItem('justdirethings:celestigem_boots', 'Ботинки скафандра из Celestigem')
  e.renameItem('justdirethings:eclipsealloy_helmet', 'Шлем скафандра из сплава Eclipse')
  e.renameItem('justdirethings:eclipsealloy_chestplate', 'Нагрудник скафандра из сплава Eclipse')
  e.renameItem('justdirethings:eclipsealloy_leggings', 'Поножи скафандра из сплава Eclipse')
  e.renameItem('justdirethings:eclipsealloy_boots', 'Ботинки скафандра из сплава Eclipse')
})
