// Banned Tags
ServerEvents.tags("item", (event) => {
    event.add("contained:banned_items", [
        "opolisutilities:cloche",
        "opolisutilities:smart_crafting_table",
        "opolisutilities:catalogue",
        "opolisutilities:catalogue_book",
        "draconicevolution:reactor_core",
        "draconicevolution:reactor_injector",
        "draconicevolution:reactor_stabilizer",
        "draconicevolution:reactor_prt_focus_ring",
        "draconicevolution:reactor_prt_in_rotor",
        "draconicevolution:reactor_prt_out_rotor",
        "draconicevolution:reactor_prt_rotor_full",
        "draconicevolution:reactor_prt_stab_frame",
        "oritech:low_yield_nuke",
        "oritech:nuke",
        "ae2:spatial_anchor",
        "draconicevolution:p2p_dislocator",
        "draconicevolution:p2p_dislocator_unbound",
        "draconicevolution:player_dislocator",
        "draconicevolution:player_dislocator_unbound",
        "oritech:reactor_controller",
        "oritech:reactor_wall",
        "oritech:reactor_rod",
        "oritech:reactor_double_rod",
        "oritech:reactor_quad_rod",
        "oritech:reactor_vent",
        "oritech:reactor_reflector",
        "oritech:reactor_heat_pipe",
        "oritech:reactor_condenser",
        "oritech:reactor_fuel_port",
        "oritech:reactor_absorber_port",
        "oritech:reactor_energy_port",
        "oritech:reactor_redstone_port",
        "energymeter:monitor",
        "strainers:iron_ore_piece",
        "strainers:copper_ore_piece",
        "strainers:tin_ore_piece",
        "strainers:silver_ore_piece",
        "strainers:lead_ore_piece",
        "strainers:nickel_ore_piece",
        "strainers:zinc_ore_piece",
        "strainers:platinum_ore_piece",
        "strainers:osmium_ore_piece",
        "strainers:uranium_ore_piece",
        "strainers:aluminum_ore_piece",
        "strainers:gold_ore_piece",
        "strainers:diamond_ore_piece",
        "strainers:emerald_ore_piece",
        "strainers:lapis_ore_piece",
        "strainers:redstone_ore_piece",
        "strainers:coal_ore_piece",
        "strainers:quartz_ore_piece",
        "strainers:debris_ore_piece",
        "strainers:stone_pebble",
        "strainers:purified_gravel",
        "strainers:purified_soul_sand",
        "strainers:purified_dirt",
        "strainers:purified_soul_soil",
        "mysticalagriculture:end_agglomeratio",
        "mysticalagriculture:prismarine_agglomeratio",
        "mysticalagriculture:honey_agglomeratio",
        "mysticalagriculture:coral_agglomeratio",
        "mysticalagriculture:nether_agglomeratio",
        "mysticalagriculture:dye_agglomeratio",
        "strainers:blazing_salt_mulch",
        "pipez:improved_upgrade",
        "supplementaries:pancake",
        'extendedae:infinity_cobblestone_cell',
        'extendedae:infinity_water_cell',
    ]);
});

// Banned Recipes
ServerEvents.recipes((event) => {
    event.remove({ output: "#contained:banned_items" });
});
